### ISSUE TITLE
Unable to build - ERROR: librtmp not found

### ISSUE THREAD

**Issue by rbiresch** [cine-io/android-ffmpeg-with-rtmp#4] opened 2014-09-09 17:09 UTC
I've followed the instructions for building however, I'm seeing ERROR: librtmp not found in the build.log.

Machine:

```
System Version: OS X 10.9.4 (13E28)
Kernel Version: Darwin 13.3.0
```

Terminal output:

```
android-ffmpeg-with-rtmp (master ✓)$ ./build.sh 
Setting up build environment ...
Looking for the NDK ...
find: /usr/sbin/authserver: Permission denied
Path to NDK [/usr/local/Cellar/android-ndk/r10/android-ndk-r10]: 
Saving configuration into /Users/rbiresch/projects/other/android-ffmpeg-with-rtmp/.build-config.sh ...
OS_ARCH=darwin-x86_64
NDK=/usr/local/Cellar/android-ndk/r10/android-ndk-r10
SYSROOT=/usr/local/Cellar/android-ndk/r10/android-ndk-r10/platforms/android-19/arch-arm
TOOLCHAIN=/usr/local/Cellar/android-ndk/r10/android-ndk-r10/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64
Building openssl-android ...
Building librtmp for android ...
Building ffmpeg for android ...
Couldn't configure ffmpeg!
Check the build log: /Users/rbiresch/projects/other/android-ffmpeg-with-rtmp/build/build.log
```

Tail of the build.log:

```
...
x ffmpeg/libavutil/xga_font_data.h
x ffmpeg/RELEASE
x ffmpeg/presets/
x ffmpeg/presets/libvpx-360p.ffpreset
x ffmpeg/presets/libvpx-1080p.ffpreset
x ffmpeg/presets/libvpx-720p50_60.ffpreset
x ffmpeg/presets/libvpx-720p.ffpreset
x ffmpeg/presets/libvpx-1080p50_60.ffpreset
x ffmpeg/ffplay.c
patching file configure
Hunk #1 succeeded at 2723 (offset 54 lines).
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
ERROR: librtmp not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
```

**Comment by jeffreywescott** [comment] 2014-09-09 19:46
Hi, @rbiresch. I'm unable to reproduce your error. What are the contents of the `build/dist/lib` directory? Do you see a `librtmp` in there anywhere?

**Comment by rbiresch** [comment] 2014-09-09 19:51
No, I don't see `librtmp` in `build/dist/lib`...this is what I have `libcrypto.so librtmp-1.so libssl.so`.  Not sure if `librtmp-1.so` is is the same library or not?

**Comment by jeffreywescott** [comment] 2014-09-09 19:59
Yep -- `librtmp-1.so` is what you want. I'm not sure what's going on, honestly. :-(

Can you post your entire `build.log`?

**Comment by rbiresch** [comment] 2014-09-09 22:30
I copied `librtmp-1.so` to `librtmp.so` and ran the build again.  This time I got this...

```
android-ffmpeg-with-rtmp (master ✓)$ ./build.sh 
Setting up build environment ...
OS_ARCH=darwin-x86_64
NDK=/usr/local/Cellar/android-ndk/r10/android-ndk-r10
SYSROOT=/usr/local/Cellar/android-ndk/r10/android-ndk-r10/platforms/android-19/arch-arm
TOOLCHAIN=/usr/local/Cellar/android-ndk/r10/android-ndk-r10/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64
Building openssl-android ...
Building librtmp for android ...
Couldn't patch librtmp Makefile!
Check the build log: /Users/rbiresch/projects/other/android-ffmpeg-with-rtmp/build/build.log
```

build.log file

```
build (master ✓)$ cat build.log 
Android NDK: WARNING:/Users/rbiresch/projects/other/android-ffmpeg-with-rtmp/src/openssl-android/crypto/Android.mk:crypto_static: LOCAL_LDLIBS is always ignored for static libraries    
[armeabi] Install        : libcrypto.so => libs/armeabi/libcrypto.so
[armeabi] Install        : openssl => libs/armeabi/openssl
[armeabi] Install        : libssl.so => libs/armeabi/libssl.so
[armeabi] Install        : ssltest => libs/armeabi/ssltest
patching file Makefile
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej
```

**Comment by jeffreywescott** [comment] 2014-09-10 00:56
Hi, @rbiresch -- that wouldn't be the problem. The `-1` is correct. Your _original_ issue is probably related to paths somehow ... like it doesn't know where to look to find the librtmp-1.so file.

This follow-up issue is most likely related to the fact that you've already patched the `ffmpeg` configure script, and it's trying to apply the patch a second time, so it fails.

As I said, without your full `build.log`, there's not much I can do. I recommend starting over from scratch, letting it fail, then sending me your `build.log`.

**Comment by rbiresch** [comment] 2014-09-10 01:52
Thanks Jeff, I've started over with the build and emailed you the build.log file.  It was too large to paste into this issue.

**Comment by jeffreywescott** [comment] 2014-09-10 05:26
Hi, @rbiresch. Can you run this command for me on your system:

``` bash
which pkg-config
```

From looking at your `build.log`, it looks like `librtmp` is _building_ correctly, and being copied to the right directory, but `pkg-config` isn't finding it.

**Comment by rbiresch** [comment] 2014-09-10 11:58
I did not have `pkg-config` installed on my machine.  I installed it with homebrew `brew install pkg-config`.  Then did a clean install and built fine.  I'm not sure why I didn't have `pkg-config` installed.  Thanks for your help!

**Comment by jeffreywescott** [comment] 2014-09-10 12:12
Glad to hear it! Closing this.

**Closed as completed by jeffreywescott** 2014-09-10 12:12 UTC

**Comment by jareiko** [comment] 2014-12-15 16:50
I also don't have pkg-config on my Mac, but I don't have homebrew either and would prefer not to install it. Is there any other workaround?

**Comment by jeffreywescott** [comment] 2014-12-15 17:40
@jareiko, while I haven't tried it, you might try this: http://macpkg.sourceforge.net/

There's no way you'll be able to build without `pkg-config`.

Also -- an OS X system without Homebrew is a sad system indeed.

**Comment by dpkirchner** [comment] 2015-03-17 21:20
FWIW, this error may not be seen if you have a version of libssl installed on your computer.

If you have libssl installed (via homebrew or whatever) pkg-config will find its pc file installed in /usr/lib/pkgconfig or /usr/share/pkgconfig depending on your system. There is no .pc file in the openssl-android directory.

Ultimately, this means that the build process will, at best, find no libssl and, at worst, assume it has a different version of libssl than it will be building against.

I don't know if these are the correct values, but here's what I added to make it work. Hoping others bumping in to this ticket may find this useful. Be sure to replace "prefix", of course.

./src/openssl-android/libssl.pc:

```
prefix=/home/vagrant/android-ffmpeg-with-rtmp/src/openssl-android
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries
Version: 1.0.0a
Requires: 
Libs: -L${libdir} -lssl -lcrypto -lz
Cflags: -I${includedir} 
```

./src/openssl-android/libcrypto.pc:

```
prefix=/home/vagrant/android-ffmpeg-with-rtmp/src/openssl-android
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: OpenSSL-crypto
Description: OpenSSL cryptography library
Version: 1.0.0a
Requires: 
Libs: -L${libdir} -lcrypto -lz
Cflags: -I${includedir} 
```
